## Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. . 

In [1]:
import numpy as np

In [2]:
#%% Ex1

#dimesio matriu
dim = np.random.randint(8,15)

#dtype = np.int64
randArray = np.random.randint(0,500, size=dim, dtype = np.int64)

print(randArray)
print('La dimensio de la matriu es', randArray.shape[0])

[404 228 308 106 199 406 205  76  92  59  19 251 229]
La dimensio de la matriu es 13


## Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [7]:
#%% Ex2

#mean
mean = np.mean(randArray)
print(mean)

minusMean = randArray-mean
print(minusMean)

256.6666666666667
[ 193.33333333 -136.66666667   57.33333333 -133.66666667  -23.66666667
  -22.66666667  -29.66666667 -132.66666667  228.33333333]


## Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [10]:
#%% Ex3

#in size pass a tuple. Matrix 5x5 ---> size=(5,5)
randMatrix = np.random.randint(0,500,(5,5))
print(randMatrix)

totalMax = np.amax(randMatrix)
print(totalMax)

#max of horizontal axis
maxX = np.amax(randMatrix,1) #axis=1 means row
print(maxX)

#max of vertical axis
maxY = np.amax(randMatrix, 0) #axis=0 means column
print(maxY)

[[253 490 114 239  29]
 [339 491 393 375 409]
 [369 169 239 207  71]
 [ 92  89 388  71 447]
 [224 158  47 466  13]]
491
[490 491 369 447 466]
[369 491 393 466 447]


## Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de
Broadcasting que diu : "les matrius es poden transmetre / broadcast si 
les seves dimensions coincideixen o si una de les matrius té una mida d'1".

**Same shape arrays**

In [ ]:
mat1 = np.random.randint(0,10,(5,5))
print(mat1)
mat2 = np.random.randint(0,10,(5,5))
print(mat1*mat2,mat1+mat2)

**An array with an escalar**

In [ ]:
#matrix with an escalar (an escalar is an array in the shape of (1,))
print(mat1*2, mat2+20)

**matrix with other matrix, different shape**
this will only work out if the size of each column is the same, or one of the arrays has one row
exactly as long as all the rows of the other array, or has one column exactly as long as the columns
of the other array.
*Mat1 is a 5x5 array

In [ ]:
mat3 = np.random.randint(0,10,(5,1))#One column, so rows of 1 element. Each row of mat1 is multiplied by the element in the row of mat3
mat3TimesMat1 = mat3 * mat1

mat4 = np.random.randint(0,10,(1,5))#One row. Each row is multiplied by the row in mat4
mat4TimesMat1 = mat1 * mat4

mat1 being a 5x5 matrix,
when the size is not 1 or equal:
    
```python
mat5 = np.random.randint(0,10,(2,5)), #two rows python cannot broadcast it

mat5TimesMat1 = mat1 * mat5
```

THIS THROWS ERROR

A more clear example

```python
mat6 = np.random.randint(0,10,(1,5)) 
mat7 = np.random.randint(0,10,(1,3)) 

mat7TimesMat6 = mat6 * mat7
```

THIS ALSO THROWS ERROR

What about random things?

```python
mat8 = np.array([[1,2,3],[1,2,3],[1,2,3]])

mat9 = np.array([[1,2]]) #However a [1,2,3] array could have been broadcast

mat10 = mat8 * mat9
```

ALSO ERROR

## Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [ ]:
matrix1 = np.random.randint(0,10,(10,7))

column0 = matrix1[:,0] 

row5 = matrix1[5,:]

#rowPlusColumn = column0+row5 this would be a broadcast error, because the matrix is not square.
#We could use something like fillWithZero if we wanted to add up both vectors.

In [13]:
rowPlusColumn = np.sum(column0) + np.sum(row5)
print(rowPlusColumn)

69


## Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [14]:
#Dividir uniformement meaning the rest is 0?
boolMatrix1 = (matrix1 % 4) == 0
print(boolMatrix1)

[[False False False False False  True  True]
 [False False  True  True  True False False]
 [False False False  True False False False]
 [False  True  True False False False False]
 [False  True  True False False  True  True]
 [ True False False False False False False]
 [ True  True  True  True  True False False]
 [False False False False  True False False]
 [ True False  True False False  True False]
 [False False False False  True  True  True]]


## Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. 
Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però 
encara obteniu les dades que esteu cercant.

In [15]:
#%% Ex7
indexedMatrix = matrix1[boolMatrix1]
print(indexedMatrix)

[8 4 0 4 4 8 8 8 8 0 4 0 8 4 0 4 0 8 4 0 8 4 0 4 0]
