## Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. . 

In [1]:
import numpy as np

In [2]:
#%% Ex1

#size of 1d array
size1D = np.random.randint(8,15)

#dtype = np.int64
randArray = np.random.randint(0,500, size=size1D, dtype = np.int64)

print(randArray)
print('La dimensio de la matriu es', randArray.ndim)

[490 436 489 237 195 438 130 478 191]
La dimensio de la matriu es 1


## Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [3]:
#%% Ex2

#mean
mean = np.mean(randArray)
print(mean)

minusMean = randArray-mean
print(minusMean)

342.6666666666667
[ 147.33333333   93.33333333  146.33333333 -105.66666667 -147.66666667
   95.33333333 -212.66666667  135.33333333 -151.66666667]


## Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [4]:
#%% Ex3

#in size pass a tuple. Matrix 5x5 ---> size=(5,5), this will be the shape
randMatrix = np.random.randint(0,500,(5,5))
print(randMatrix)

totalMax = np.amax(randMatrix)
print(totalMax)

#max of horizontal axis
maxX = np.amax(randMatrix,1) #axis=1 means row
print(maxX)

#max of vertical axis
maxY = np.amax(randMatrix, 0) #axis=0 means column
print(maxY)

[[301 309 184 498 194]
 [451 251 244 154 149]
 [179 245 286 175 305]
 [132 387  97 462 152]
 [ 44 337 400  14 496]]
498
[498 451 305 462 496]
[451 387 400 498 496]


## Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de
Broadcasting que diu : "les matrius es poden transmetre / broadcast si 
les seves dimensions coincideixen o si una de les matrius té una mida d'1".

**Same shape arrays**

In [5]:
mat1 = np.random.randint(0,10,(5,5))
print(mat1)
mat2 = np.random.randint(0,10,(5,5))
print(mat1*mat2,mat1+mat2)

[[2 9 0 2 5]
 [0 2 3 9 5]
 [2 7 8 0 7]
 [0 2 2 8 4]
 [1 3 5 4 3]]
[[10 18  0  8 45]
 [ 0  2  6 36  5]
 [ 8 28  0  0 42]
 [ 0  0  0  8  0]
 [ 7 15 10  4  0]] [[ 7 11  5  6 14]
 [ 8  3  5 13  6]
 [ 6 11  8  1 13]
 [ 3  2  2  9  4]
 [ 8  8  7  5  3]]


**An array with an escalar**

In [6]:
#matrix with an escalar (an escalar is an array in the shape of (1,))
print(mat1*2, mat2+20)

[[ 4 18  0  4 10]
 [ 0  4  6 18 10]
 [ 4 14 16  0 14]
 [ 0  4  4 16  8]
 [ 2  6 10  8  6]] [[25 22 25 24 29]
 [28 21 22 24 21]
 [24 24 20 21 26]
 [23 20 20 21 20]
 [27 25 22 21 20]]


**matrix with other matrix, different shape**
this will only work out if the size of each column is the same, or one of the arrays has one row
exactly as long as all the rows of the other array, or has one column exactly as long as the columns
of the other array.
*Mat1 is a 5x5 array

In [7]:
mat3 = np.random.randint(0,10,(5,1))#One column, so rows of 1 element. Each row of mat1 is multiplied by the element in the row of mat3
mat3TimesMat1 = mat3 * mat1

mat4 = np.random.randint(0,10,(1,5))#One row. Each row is multiplied by the row in mat4
mat4TimesMat1 = mat1 * mat4

mat1 being a 5x5 matrix,
when the size is not 1 or equal:
    
```python
mat5 = np.random.randint(0,10,(2,5)), #two rows python cannot broadcast it

mat5TimesMat1 = mat1 * mat5
```

THIS THROWS ERROR

A more clear example

```python
mat6 = np.random.randint(0,10,(1,5)) 
mat7 = np.random.randint(0,10,(1,3)) 

mat7TimesMat6 = mat6 * mat7
```

THIS ALSO THROWS ERROR

What about random things?

```python
mat8 = np.array([[1,2,3],[1,2,3],[1,2,3]])

mat9 = np.array([[1,2]]) #However a [1,2,3] array could have been broadcast

mat10 = mat8 * mat9
```

ALSO ERROR

## Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [8]:
matrix1 = np.random.randint(0,10,(10,7))

column0 = matrix1[:,0] 

row5 = matrix1[5,:]

#rowPlusColumn = column0+row5 this would be a broadcast error, because the matrix is not square.
#We could use something like fillWithZero if we wanted to add up both vectors.

In [9]:
rowPlusColumn = np.sum(column0) + np.sum(row5)
print(rowPlusColumn)

87


## Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [10]:
#Dividir uniformement meaning the rest is 0?
boolMatrix1 = (matrix1 % 4) == 0
print(boolMatrix1)

[[ True False False False  True False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True False False False  True False  True]
 [False  True False  True  True False  True]
 [False False False False False False False]
 [ True False False  True  True False False]
 [False False False False False False False]
 [ True False  True  True False False False]
 [False  True  True False False False  True]]


## Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. 
Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però 
encara obteniu les dades que esteu cercant.

In [11]:
#%% Ex7
indexedMatrix = matrix1[boolMatrix1]
print(indexedMatrix)

[4 8 8 4 8 8 4 4 8 0 8 4 8 0 0 4 8 4]
